// DO NOT EDIT THIS FILE BY HAND.
//
// This file was automagically generated with:
// template: libs/jsruntime/src/bridge/llvmir/type_holder.hh.njk

#pragma once

#include <cstdlib>

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-parameter"
#include <llvm/IR/IRBuilder.h>
#include <llvm/IR/LLVMContext.h>
#include <llvm/IR/Module.h>
#pragma GCC diagnostic pop

class TypeHolder {
 public:
  TypeHolder(llvm::LLVMContext& context, llvm::Module& module, llvm::IRBuilder<>& builder)
      : context_(context), module_(module), builder_(builder) {}

  llvm::Type* GetWordType();
  llvm::Value* GetWord(size_t value);
  llvm::StructType* CreateValueType();
  llvm::StructType* CreateBindingType();
  llvm::FunctionType* CreateFunctionType();
  llvm::Function* CreateRuntimeToBoolean();
  llvm::Function* CreateRuntimeToNumeric();

 private:
  llvm::LLVMContext& context_;
  llvm::Module& module_;
  llvm::IRBuilder<>& builder_;
  llvm::StructType* value_type_ = nullptr;
  llvm::StructType* binding_type_ = nullptr;
  llvm::FunctionType* function_type_ = nullptr;
  llvm::Function* runtime_to_boolean_ = nullptr;
  llvm::Function* runtime_to_numeric_ = nullptr;
};
