[package]
name = "bee-htmlparser"
version = "0.1.0"
edition = "2021"
authors = ["BEE project contributors"]
publish = false

[dependencies]
bee-htmltokenizer = { path = "../htmltokenizer" }
flagset = "0.4.3"
phf = { version = "0.11.1", features = ["macros"] }
thiserror = "1.0.40"
tracing = "0.1.37"
unicase = "2.6.0"

[dev-dependencies]
anyhow = "1.0.71"
bee-toydom = { path = "../toydom" }
criterion = "0.4.0"
ctor = "0.2.0"
tracing-subscriber = "0.3.17"

[lib]
bench = false

[[bench]]
name = "bee-htmlparser-bench"
path = "benches/htmlparser_bench.rs"
harness = false

[[example]]
name = "bee-htmlparser-demo"
path = "examples/demo.rs"
