print(String()); ///=""
print(String(undefined)); ///="undefined"
print(String(null)); ///="null"
print(String(true)); ///="true"
print(String(false)); ///="false"
print(String(1)); ///="1"
print(String('a')); ///="a"
print(String({})); ///="[object Object]"
print(new String(1)) ///=object
