print(typeof undefined); ///="undefined"
print(typeof null); ///="object"
print(typeof true); ///="boolean"
print(typeof 1); ///="number"
print(typeof "hi"); ///="string"
print(typeof {}); ///="object"
print(typeof function() {}); ///="function"
print(typeof (() => 0)); ///="function"
print(typeof async function() {}); ///="function"
print(typeof (async () => 0)); ///="function"
print(typeof (async () => 0)()); ///="object"
