// DO NOT EDIT THIS FILE BY HAND.
//
// This file was automagically generated by:
// bee-tools-codegen.js --input-stdin doctype.rs.hbs

use super::*;

impl<W> TreeBuilder<W>
where
    W: DocumentWriter,
{
    #[tracing::instrument(level = "debug", skip_all)]
    pub fn handle_doctype(&mut self, doctype: Doctype<'_>) -> Control {
        tracing::debug!(mode = ?self.mode, ?doctype);
        self.ignore_lf = false;
        loop {
            match self.mode {
                mode!(Initial) => {
                    let ctrl = {
                        if let Some("html") = doctype.name {
                            // TODO: Parse error.
                        } else if let Some(_) = doctype.public_id {
                            // TODO: Parse error.
                        } else if let Some(system_id) = doctype.system_id {
                            if system_id != "about:legacy-compat" {
                                // TODO: Parse error.
                            }
                        }
                        self.append_doctype(&doctype);
                        self.determine_quirks_mode(&doctype);
                        self.switch_to(mode!(BeforeHtml));
                        Control::Continue
                    };
                    match ctrl {
                        Control::Reprocess => continue,
                        _ => return ctrl,
                    }
                }
                mode!(
                    BeforeHtml,
                    BeforeHead,
                    InHead,
                    InHeadNoscript,
                    AfterHead,
                    InBody,
                    InTable,
                    InCaption,
                    InColumnGroup,
                    InTableBody,
                    InRow,
                    InCell,
                    InSelect,
                    InSelectInTable,
                    InTemplate,
                    AfterBody,
                    InFrameset,
                    AfterFrameset,
                    AfterAfterBody,
                    AfterAfterFrameset
                ) => {
                    let ctrl = {
                        // TODO: Parse error.
                        // Ignore the token.
                        Control::Continue
                    };
                    match ctrl {
                        Control::Reprocess => continue,
                        _ => return ctrl,
                    }
                }
                mode!(InTableText) => {
                    let ctrl = {
                        // TODO
                        if !self.text.is_empty() {
                            self.insert_text_to_foster_parent();
                        }
                        self.switch_to_original_mode();
                        Control::Reprocess
                    };
                    match ctrl {
                        Control::Reprocess => continue,
                        _ => return ctrl,
                    }
                }
                mode!(Text) => {
                    unreachable!();
                }
            }
        }
    }

    fn determine_quirks_mode(&mut self, doctype: &Doctype<'_>) {
        // TODO
    }
}
