[package]
name = "xtask"
version = "0.0.0"
edition = "2021"
authors = ["BEE project contributors"]
publish = false

[dependencies]
anyhow = "1.0.70"
bee-htmlparser = { path = "../libs/htmlparser" }
bee-toydom = { path = "../libs/toydom" }
clap = { version = "4.2.4", features = ["derive"] }
