jobs:
  arm-linux-build:
    strategy:
      matrix:
        target:
          - arm-unknown-linux-gnueabi
          - armv7-unknown-linux-gnueabihf
          - aarch64-unknown-linux-gnu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - uses: actions/setup-node@v2-beta
      - name: Install npm packages
        run: npm install
        working-directory: ./tools
      - name: Update PATH
        run: |
            echo "$GITHUB_WORKSPACE/tools/bin" >>$GITHUB_PATH
            echo "$GITHUB_WORKSPACE/tools/node_modules/.bin" >>$GITHUB_PATH
      - name: Build
        run: make
        env:
          CARGO_TERM_VERBOSE: true
      - name: Run tests
        run: make test
        env:
          CARGO_TERM_VERBOSE: true
