jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v2
        with:
          # Use a Personal Access Token instead of GITHUB_TOKEN.
          #
          # Scripts using GITHUB_TOKEN cannot trigger new workflow runs.
          # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#triggering-new-workflows-using-a-personal-access-token
          github-token: ${{secrets.GH_TOKEN}}
          script: |
            await github.pulls.createReview({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number,
              event: 'APPROVE'
            })
            await github.pulls.merge({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number
            })
