name: CI

on:
  push:
    branches:
      - master

jobs:
  linux-build:
  macos-build:
  windows-build:
  arm-linux-build:
  coverage:
    needs:
      - linux-build
      - macos-build
      - windows-build
      - arm-linux-build
