jobs:
  coverage:
    env:
      DENO_DIR: /tmp/deno
    runs-on: ubuntu-20.04
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x
      - name: Cache for deno
        uses: actions/cache@v2
        with:
          path: $DENO_DIR
          key: ${{ runner.os }}-deno-${{ hashFiles("tools/deps.js") }}
          restore-keys: |
            ${{ runner.os }}-deno-
      - uses: actions/setup-node@v2
      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - name: Cache for npm
        uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-npm-${{ hashFiles("**/package-lock.json") }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Clean
        run: |
          make clean
      - name: Prepare GitHub CI
        run: |
          make github-ci
      - name: Generate coverage data
        run: |
          make coverage-lcov
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: target/coverage/lcov.info
