jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - uses: actions/setup-node@v2-beta
      - name: Install npm packages
        run: npm install
        working-directory: ./tools
      - name: Update PATH
        run: |
            echo "$GITHUB_WORKSPACE/tools/bin" >>$GITHUB_PATH
            echo "$GITHUB_WORKSPACE/tools/node_modules/.bin" >>$GITHUB_PATH
      - name: Generate coverage data
        run: make coverage
      - uses: actions-rs/grcov@v0.1
        id: coverage
      - name: Upload coverage data to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ${{ steps.coverage.outputs.report }}
