jobs:
  cross-build:
    strategy:
      matrix:
        runner:
          - ubuntu-20.04
        target:
          - arm-unknown-linux-gnueabi
          - armv7-unknown-linux-gnueabihf
          - aarch64-unknown-linux-gnu
        rust:
          - stable
          #- nightly
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
          override: true
      - uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x
      - uses: actions/setup-node@v2-beta
      - name: Install packages for tools
        run: npm install
        working-directory: ./tools
      - name: Install packages for webui
        run: npm install
        working-directory: ./webui
      - name: Update PATH
        run: |
            echo "$GITHUB_WORKSPACE/tools/bin" >>$GITHUB_PATH
            echo "$GITHUB_WORKSPACE/tools/node_modules/.bin" >>$GITHUB_PATH
      - name: Build
        run: make
        env:
          CARGO_TERM_VERBOSE: true
      - name: Run tests
        run: make test
        env:
          CARGO_TERM_VERBOSE: true
