name: Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  build:
  coverage:
    needs:
      - build
  auto-merge:
    if: github.actor == 'dependabot[bot]'
    needs:
      - build
