[package]
name = "bee-dfagen"
version = "0.0.0"
edition = "2021"
authors = ["BEE project contributors"]
publish = false

[dependencies]
anyhow = "1.0.75"
bee-macros = { path = "../macros" }
clap = { version = "4.4.8", features = ["derive", "env"] }
indexmap = { version = "2.1.0", features = ["serde"] }
maplit = "1.0.2"
serde = { version = "1.0.192", features = ["derive", "rc"] }
serde_json = "1.0.108"
serde_yaml = "0.9.27"
smallvec = "1.11.2"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "json"] }

[dev-dependencies]
test-log = { version = "0.2.13", default-features = false, features = ["trace"] }
