[package]
name = "bee-dfagen"
version = "0.0.0"
edition = "2021"
authors = ["BEE project contributors"]
publish = false

[dependencies]
anyhow = "1.0.71"
bee-macros = { path = "../macros" }
clap = { version = "4.3.11", features = ["derive"] }
indexmap = "2.0.0"
maplit = "1.0.2"
serde = { version = "1.0.169", features = ["derive", "rc"] }
serde_json = "1.0.100"
serde_yaml = "0.9.22"
smallvec = "1.11.0"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
