[package]
name = "bee-dfagen"
version = "0.0.0"
edition = "2021"
authors = ["BEE project contributors"]
publish = false

[dependencies]
anyhow = "1.0.72"
bee-macros = { path = "../macros" }
clap = { version = "4.3.21", features = ["derive", "env"] }
indexmap = "2.0.0"
maplit = "1.0.2"
serde = { version = "1.0.183", features = ["derive", "rc"] }
serde_json = "1.0.104"
serde_yaml = "0.9.25"
smallvec = "1.11.0"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter", "json"] }
