[package]
name = "estree"
version = "0.0.0"
edition = "2021"
authors = ["BEE project contributors"]
publish = false

[dependencies]
anyhow = "1.0.89"
assert-json-diff = "2.0.2"
clap = { version = "4.5.19", features = ["env", "derive", "wrap_help"] }
jsparser = { path = "../../libs/jsparser", features = ["location"] }
logging = { path = "../../libs/logging" }
serde = { version = "1.0.210", features = ["derive", "rc"] }
serde_json = { version = "1.0.128", features = ["preserve_order"] }
