[package]
name = "estree"
version = "0.0.0"
edition = "2021"
authors = ["BEE project contributors"]
publish = false

[dependencies]
anyhow = "1.0.79"
assert-json-diff = "2.0.2"
clap = { version = "4.4.14", features = ["env", "derive", "wrap_help"] }
jsparser = { path = "../../libs/jsparser", features = ["location"] }
serde = { version = "1.0.195", features = ["derive", "rc"] }
logging = { path = "../../libs/logging" }
serde_json = { version = "1.0.111", features = ["preserve_order"] }

[dev-dependencies]
anyhow = "1.0.79"
test-log = { version = "0.2.14", default-features = false, features = ["trace"] }
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "json"] }
