[package]
name = "dfagen"
version = "0.0.0"
edition = "2021"
authors = ["BEE project contributors"]
publish = false

[dependencies]
anyhow = "1.0.86"
base = { path = "../../libs/base" }
clap = { version = "4.5.15", features = ["derive", "env"] }
indexmap = { version = "2.4.0", features = ["serde"] }
logging = { path = "../../libs/logging" }
maplit = "1.0.2"
serde = { version = "1.0.207", features = ["derive", "rc"] }
serde_json = "1.0.124"
serde_yaml = "0.9.34"
smallvec = "1.13.2"
