[package]
name = "dfagen"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
anyhow = "1.0.94"
base = { path = "../../libs/base" }
clap = { version = "4.5.21", features = ["derive", "env"] }
indexmap = { version = "2.7.0", features = ["serde"] }
logging = { path = "../../libs/logging" }
maplit = "1.0.2"
serde = { version = "1.0.215", features = ["derive", "rc"] }
serde_json = "1.0.133"
serde_yaml = "0.9.34"
smallvec = "1.13.2"
