[package]
name = "dfagen"
version = "0.0.0"
edition = "2021"
authors = ["BEE project contributors"]
publish = false

[dependencies]
anyhow = "1.0.79"
base = { path = "../../libs/base" }
clap = { version = "4.4.18", features = ["derive", "env"] }
indexmap = { version = "2.2.1", features = ["serde"] }
logging = { path = "../../libs/logging" }
maplit = "1.0.2"
serde = { version = "1.0.196", features = ["derive", "rc"] }
serde_json = "1.0.111"
serde_yaml = "0.9.30"
smallvec = "1.13.1"
