[package]
name = "bee-jsparser"
version = "0.1.0"
edition = "2021"
authors = ["BEE project contributors"]
publish = false

[dependencies]
phf = { version = "0.11.2", features = ["macros"] }
tracing = "0.1.37"

[dev-dependencies]
anyhow = "1.0.72"
clap = { version = "4.3.21", features = ["env", "derive", "wrap_help"] }
humantime = "2.1.0"
test-log = { version = "0.2.12", default-features = false, features = ["trace"] }
tracing-subscriber = { version = "0.3.17", features = ["env-filter", "json"] }

[lib]
bench = false

[[example]]
name = "bee-jsparser-demo"
path = "examples/demo.rs"
