[package]
name = "bee-jsparser"
version = "0.1.0"
edition = "2021"
authors = ["BEE project contributors"]
publish = false

[dependencies]
unicode-id-start = "1.1.2"
phf = { version = "0.11.2", features = ["macros"] }
tracing = "0.1.40"

[dev-dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.8", features = ["env", "derive", "wrap_help"] }
test-log = { version = "0.2.13", default-features = false, features = ["trace"] }
tracing-subscriber = { version = "0.3.17", features = ["env-filter", "json"] }

[lib]
bench = false

[[example]]
name = "bee-jsparser-demo"
path = "examples/demo.rs"
