[package]
name = "bee-handlebars"
version = "0.0.0"
edition = "2021"
authors = ["BEE project contributors"]
publish = false
description = "A tool to render a Handlebars template file"

[dependencies]
anyhow = "1.0.72"
clap = { version = "4.3.21", features = ["derive", "unicode", "wrap_help"] }
handlebars = { version = "4.3.7", features = ["dir_source"] }
serde = { version = "1.0.183", features = ["derive"] }
serde_json = "1.0.104"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
