version: '3.7'

services:
  devenv:
    image: 'bee-project/devenv'
    build:
      context: .
    command: |-
      /bin/sh -c "while sleep 1000; do :; done"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - 'seccomp:unconfined'
    volumes:
      - ..:/workspaces:cached
      #- target:/workspaces/target
      - node_modules:/workspaces/tools/node_modules

volumes:
  # TODO
  # ----
  # Use a local volume for the target dir
  #
  # target:
  #   name: bee_devenv_target_volume
  #   driver: local
  node_modules:
    name: bee_devenv_node_modules_volume
    driver: local
