[package]
name = "bee-layout"
version = "0.1.0"
authors = ["BEE project contributors"]
edition = "2021"
publish = false

[features]
service = ["bee-geometry/serde", "serde", "serde_json"]

[dependencies]
anyhow = "1.0.75"
bee-geometry = { path = "../geometry" }
num-traits = "0.2.17"
serde = { version = "1.0.190", features = ["derive", "rc"], optional = true }
serde_json = { version = "1.0.108", optional = true }
tracing = "0.1.40"

[dev-dependencies]
assert-json-diff = "2.0.2"
assert_matches = "1.5.0"
serde_json = "1.0.108"
serde_yaml = "0.9.27"

[lib]
bench = false
