// DO NOT EDIT THIS FILE BY HAND.
//
// This file was automagically generated with:
// template: libs/jsruntime/src/llvmir/type_holder.cc.njk

#include "type_holder.hh"

llvm::StructType* TypeHolder::CreateValueType() {
  if (value_type_ == nullptr) {
    value_type_ = llvm::StructType::create(context_, "Value");
    value_type_->setBody({builder_.getInt64Ty(), builder_.getInt64Ty()});
  }
  return value_type_;
}

llvm::Function* TypeHolder::CreateToBoolean() {
  if (to_boolean_ == nullptr) {
    auto* prototype = llvm::FunctionType::get(builder_.getInt1Ty(), {builder_.getPtrTy()}, false);
    to_boolean_ =
        llvm::Function::Create(prototype, llvm::Function::ExternalLinkage, "to_boolean", module_);
  }
  return to_boolean_;
}

llvm::Function* TypeHolder::CreateToNumeric() {
  if (to_numeric_ == nullptr) {
    auto* prototype =
        llvm::FunctionType::get(builder_.getDoubleTy(), {builder_.getPtrTy()}, false);
    to_numeric_ =
        llvm::Function::Create(prototype, llvm::Function::ExternalLinkage, "to_numeric", module_);
  }
  return to_numeric_;
}

llvm::Function* TypeHolder::CreateRuntimeDeclareImmutable() {
  if (runtime_declare_immutable_ == nullptr) {
    auto* prototype = llvm::FunctionType::get(builder_.getVoidTy(),
        {builder_.getPtrTy(), builder_.getInt32Ty(), builder_.getInt32Ty(), builder_.getPtrTy()},
        false);
    runtime_declare_immutable_ = llvm::Function::Create(
        prototype, llvm::Function::ExternalLinkage, "runtime_declare_immutable", module_);
  }
  return runtime_declare_immutable_;
}

llvm::Function* TypeHolder::CreateRuntimeDeclareImmutableUndefined() {
  if (runtime_declare_immutable_undefined_ == nullptr) {
    auto* prototype = llvm::FunctionType::get(builder_.getVoidTy(),
        {builder_.getPtrTy(), builder_.getInt32Ty(), builder_.getInt32Ty()}, false);
    runtime_declare_immutable_undefined_ = llvm::Function::Create(prototype,
        llvm::Function::ExternalLinkage, "runtime_declare_immutable_undefined", module_);
  }
  return runtime_declare_immutable_undefined_;
}

llvm::Function* TypeHolder::CreateRuntimeDeclareImmutableBoolean() {
  if (runtime_declare_immutable_boolean_ == nullptr) {
    auto* prototype = llvm::FunctionType::get(builder_.getVoidTy(),
        {builder_.getPtrTy(), builder_.getInt32Ty(), builder_.getInt32Ty(), builder_.getInt1Ty()},
        false);
    runtime_declare_immutable_boolean_ = llvm::Function::Create(
        prototype, llvm::Function::ExternalLinkage, "runtime_declare_immutable_boolean", module_);
  }
  return runtime_declare_immutable_boolean_;
}

llvm::Function* TypeHolder::CreateRuntimeDeclareImmutableNumber() {
  if (runtime_declare_immutable_number_ == nullptr) {
    auto* prototype = llvm::FunctionType::get(builder_.getVoidTy(),
        {builder_.getPtrTy(), builder_.getInt32Ty(), builder_.getInt32Ty(),
            builder_.getDoubleTy()},
        false);
    runtime_declare_immutable_number_ = llvm::Function::Create(
        prototype, llvm::Function::ExternalLinkage, "runtime_declare_immutable_number", module_);
  }
  return runtime_declare_immutable_number_;
}

llvm::Function* TypeHolder::CreateRuntimeDeclareMutable() {
  if (runtime_declare_mutable_ == nullptr) {
    auto* prototype = llvm::FunctionType::get(builder_.getVoidTy(),
        {builder_.getPtrTy(), builder_.getInt32Ty(), builder_.getInt32Ty(), builder_.getPtrTy()},
        false);
    runtime_declare_mutable_ = llvm::Function::Create(
        prototype, llvm::Function::ExternalLinkage, "runtime_declare_mutable", module_);
  }
  return runtime_declare_mutable_;
}

llvm::Function* TypeHolder::CreateRuntimeDeclareMutableUndefined() {
  if (runtime_declare_mutable_undefined_ == nullptr) {
    auto* prototype = llvm::FunctionType::get(builder_.getVoidTy(),
        {builder_.getPtrTy(), builder_.getInt32Ty(), builder_.getInt32Ty()}, false);
    runtime_declare_mutable_undefined_ = llvm::Function::Create(
        prototype, llvm::Function::ExternalLinkage, "runtime_declare_mutable_undefined", module_);
  }
  return runtime_declare_mutable_undefined_;
}

llvm::Function* TypeHolder::CreateRuntimeDeclareMutableBoolean() {
  if (runtime_declare_mutable_boolean_ == nullptr) {
    auto* prototype = llvm::FunctionType::get(builder_.getVoidTy(),
        {builder_.getPtrTy(), builder_.getInt32Ty(), builder_.getInt32Ty(), builder_.getInt1Ty()},
        false);
    runtime_declare_mutable_boolean_ = llvm::Function::Create(
        prototype, llvm::Function::ExternalLinkage, "runtime_declare_mutable_boolean", module_);
  }
  return runtime_declare_mutable_boolean_;
}

llvm::Function* TypeHolder::CreateRuntimeDeclareMutableNumber() {
  if (runtime_declare_mutable_number_ == nullptr) {
    auto* prototype = llvm::FunctionType::get(builder_.getVoidTy(),
        {builder_.getPtrTy(), builder_.getInt32Ty(), builder_.getInt32Ty(),
            builder_.getDoubleTy()},
        false);
    runtime_declare_mutable_number_ = llvm::Function::Create(
        prototype, llvm::Function::ExternalLinkage, "runtime_declare_mutable_number", module_);
  }
  return runtime_declare_mutable_number_;
}

llvm::Function* TypeHolder::CreateRuntimeDeclareFunction() {
  if (runtime_declare_function_ == nullptr) {
    auto* prototype = llvm::FunctionType::get(builder_.getVoidTy(),
        {builder_.getPtrTy(), builder_.getInt32Ty(), builder_.getInt32Ty(), builder_.getInt32Ty()},
        false);
    runtime_declare_function_ = llvm::Function::Create(
        prototype, llvm::Function::ExternalLinkage, "runtime_declare_function", module_);
  }
  return runtime_declare_function_;
}

llvm::Function* TypeHolder::CreateRuntimeGetBinding() {
  if (runtime_get_binding_ == nullptr) {
    auto* prototype = llvm::FunctionType::get(builder_.getVoidTy(),
        {builder_.getPtrTy(), builder_.getInt32Ty(), builder_.getInt32Ty(), builder_.getPtrTy()},
        false);
    runtime_get_binding_ = llvm::Function::Create(
        prototype, llvm::Function::ExternalLinkage, "runtime_get_binding", module_);
  }
  return runtime_get_binding_;
}

llvm::Function* TypeHolder::CreateRuntimeGetBindingBoolean() {
  if (runtime_get_binding_boolean_ == nullptr) {
    auto* prototype = llvm::FunctionType::get(builder_.getInt1Ty(),
        {builder_.getPtrTy(), builder_.getInt32Ty(), builder_.getInt32Ty()}, false);
    runtime_get_binding_boolean_ = llvm::Function::Create(
        prototype, llvm::Function::ExternalLinkage, "runtime_get_binding_boolean", module_);
  }
  return runtime_get_binding_boolean_;
}

llvm::Function* TypeHolder::CreateRuntimeGetBindingNumber() {
  if (runtime_get_binding_number_ == nullptr) {
    auto* prototype = llvm::FunctionType::get(builder_.getDoubleTy(),
        {builder_.getPtrTy(), builder_.getInt32Ty(), builder_.getInt32Ty()}, false);
    runtime_get_binding_number_ = llvm::Function::Create(
        prototype, llvm::Function::ExternalLinkage, "runtime_get_binding_number", module_);
  }
  return runtime_get_binding_number_;
}

llvm::Function* TypeHolder::CreateRuntimePutBinding() {
  if (runtime_put_binding_ == nullptr) {
    auto* prototype = llvm::FunctionType::get(builder_.getVoidTy(),
        {builder_.getPtrTy(), builder_.getInt32Ty(), builder_.getInt32Ty(), builder_.getPtrTy()},
        false);
    runtime_put_binding_ = llvm::Function::Create(
        prototype, llvm::Function::ExternalLinkage, "runtime_put_binding", module_);
  }
  return runtime_put_binding_;
}

llvm::Function* TypeHolder::CreateRuntimePutBindingUndefined() {
  if (runtime_put_binding_undefined_ == nullptr) {
    auto* prototype = llvm::FunctionType::get(builder_.getVoidTy(),
        {builder_.getPtrTy(), builder_.getInt32Ty(), builder_.getInt32Ty()}, false);
    runtime_put_binding_undefined_ = llvm::Function::Create(
        prototype, llvm::Function::ExternalLinkage, "runtime_put_binding_undefined", module_);
  }
  return runtime_put_binding_undefined_;
}

llvm::Function* TypeHolder::CreateRuntimePutBindingBoolean() {
  if (runtime_put_binding_boolean_ == nullptr) {
    auto* prototype = llvm::FunctionType::get(builder_.getVoidTy(),
        {builder_.getPtrTy(), builder_.getInt32Ty(), builder_.getInt32Ty(), builder_.getInt1Ty()},
        false);
    runtime_put_binding_boolean_ = llvm::Function::Create(
        prototype, llvm::Function::ExternalLinkage, "runtime_put_binding_boolean", module_);
  }
  return runtime_put_binding_boolean_;
}

llvm::Function* TypeHolder::CreateRuntimePutBindingNumber() {
  if (runtime_put_binding_number_ == nullptr) {
    auto* prototype = llvm::FunctionType::get(builder_.getVoidTy(),
        {builder_.getPtrTy(), builder_.getInt32Ty(), builder_.getInt32Ty(),
            builder_.getDoubleTy()},
        false);
    runtime_put_binding_number_ = llvm::Function::Create(
        prototype, llvm::Function::ExternalLinkage, "runtime_put_binding_number", module_);
  }
  return runtime_put_binding_number_;
}

llvm::Function* TypeHolder::CreateRuntimePushArgument() {
  if (runtime_push_argument_ == nullptr) {
    auto* prototype = llvm::FunctionType::get(
        builder_.getVoidTy(), {builder_.getPtrTy(), builder_.getPtrTy()}, false);
    runtime_push_argument_ = llvm::Function::Create(
        prototype, llvm::Function::ExternalLinkage, "runtime_push_argument", module_);
  }
  return runtime_push_argument_;
}

llvm::Function* TypeHolder::CreateRuntimePushArgumentUndefined() {
  if (runtime_push_argument_undefined_ == nullptr) {
    auto* prototype = llvm::FunctionType::get(builder_.getVoidTy(), {builder_.getPtrTy()}, false);
    runtime_push_argument_undefined_ = llvm::Function::Create(
        prototype, llvm::Function::ExternalLinkage, "runtime_push_argument_undefined", module_);
  }
  return runtime_push_argument_undefined_;
}

llvm::Function* TypeHolder::CreateRuntimePushArgumentBoolean() {
  if (runtime_push_argument_boolean_ == nullptr) {
    auto* prototype = llvm::FunctionType::get(
        builder_.getVoidTy(), {builder_.getPtrTy(), builder_.getInt1Ty()}, false);
    runtime_push_argument_boolean_ = llvm::Function::Create(
        prototype, llvm::Function::ExternalLinkage, "runtime_push_argument_boolean", module_);
  }
  return runtime_push_argument_boolean_;
}

llvm::Function* TypeHolder::CreateRuntimePushArgumentNumber() {
  if (runtime_push_argument_number_ == nullptr) {
    auto* prototype = llvm::FunctionType::get(
        builder_.getVoidTy(), {builder_.getPtrTy(), builder_.getDoubleTy()}, false);
    runtime_push_argument_number_ = llvm::Function::Create(
        prototype, llvm::Function::ExternalLinkage, "runtime_push_argument_number", module_);
  }
  return runtime_push_argument_number_;
}

llvm::Function* TypeHolder::CreateRuntimeCall() {
  if (runtime_call_ == nullptr) {
    auto* prototype = llvm::FunctionType::get(builder_.getVoidTy(),
        {builder_.getPtrTy(), builder_.getPtrTy(), builder_.getPtrTy()}, false);
    runtime_call_ = llvm::Function::Create(
        prototype, llvm::Function::ExternalLinkage, "runtime_call", module_);
  }
  return runtime_call_;
}

llvm::Function* TypeHolder::CreateRuntimeReturnValue() {
  if (runtime_return_value_ == nullptr) {
    auto* prototype = llvm::FunctionType::get(
        builder_.getVoidTy(), {builder_.getPtrTy(), builder_.getPtrTy()}, false);
    runtime_return_value_ = llvm::Function::Create(
        prototype, llvm::Function::ExternalLinkage, "runtime_return_value", module_);
  }
  return runtime_return_value_;
}

llvm::Function* TypeHolder::CreateRuntimeReturnBoolean() {
  if (runtime_return_boolean_ == nullptr) {
    auto* prototype = llvm::FunctionType::get(
        builder_.getVoidTy(), {builder_.getPtrTy(), builder_.getInt1Ty()}, false);
    runtime_return_boolean_ = llvm::Function::Create(
        prototype, llvm::Function::ExternalLinkage, "runtime_return_boolean", module_);
  }
  return runtime_return_boolean_;
}

llvm::Function* TypeHolder::CreateRuntimeReturnNumber() {
  if (runtime_return_number_ == nullptr) {
    auto* prototype = llvm::FunctionType::get(
        builder_.getVoidTy(), {builder_.getPtrTy(), builder_.getDoubleTy()}, false);
    runtime_return_number_ = llvm::Function::Create(
        prototype, llvm::Function::ExternalLinkage, "runtime_return_number", module_);
  }
  return runtime_return_number_;
}

llvm::Function* TypeHolder::CreateRuntimeAllocateBindings() {
  if (runtime_allocate_bindings_ == nullptr) {
    auto* prototype = llvm::FunctionType::get(
        builder_.getVoidTy(), {builder_.getPtrTy(), builder_.getInt16Ty()}, false);
    runtime_allocate_bindings_ = llvm::Function::Create(
        prototype, llvm::Function::ExternalLinkage, "runtime_allocate_bindings", module_);
  }
  return runtime_allocate_bindings_;
}

llvm::Function* TypeHolder::CreateRuntimeReleaseBindings() {
  if (runtime_release_bindings_ == nullptr) {
    auto* prototype = llvm::FunctionType::get(
        builder_.getVoidTy(), {builder_.getPtrTy(), builder_.getInt16Ty()}, false);
    runtime_release_bindings_ = llvm::Function::Create(
        prototype, llvm::Function::ExternalLinkage, "runtime_release_bindings", module_);
  }
  return runtime_release_bindings_;
}

llvm::Function* TypeHolder::CreateRuntimeInspect() {
  if (runtime_inspect_ == nullptr) {
    auto* prototype = llvm::FunctionType::get(
        builder_.getVoidTy(), {builder_.getPtrTy(), builder_.getPtrTy()}, false);
    runtime_inspect_ = llvm::Function::Create(
        prototype, llvm::Function::ExternalLinkage, "runtime_inspect", module_);
  }
  return runtime_inspect_;
}

llvm::Function* TypeHolder::CreateRuntimeInspectBoolean() {
  if (runtime_inspect_boolean_ == nullptr) {
    auto* prototype = llvm::FunctionType::get(
        builder_.getVoidTy(), {builder_.getPtrTy(), builder_.getInt1Ty()}, false);
    runtime_inspect_boolean_ = llvm::Function::Create(
        prototype, llvm::Function::ExternalLinkage, "runtime_inspect_boolean", module_);
  }
  return runtime_inspect_boolean_;
}

llvm::Function* TypeHolder::CreateRuntimeInspectNumber() {
  if (runtime_inspect_number_ == nullptr) {
    auto* prototype = llvm::FunctionType::get(
        builder_.getVoidTy(), {builder_.getPtrTy(), builder_.getDoubleTy()}, false);
    runtime_inspect_number_ = llvm::Function::Create(
        prototype, llvm::Function::ExternalLinkage, "runtime_inspect_number", module_);
  }
  return runtime_inspect_number_;
}
