[package]
name = "jstb"
version = "0.0.0"
edition = "2021"
authors = ["BEE project contributors"]
publish = false

[dependencies]
anyhow = "1.0.89"
clap = { version = "4.5.19", features = ["env", "derive", "wrap_help"] }
jsruntime = { path = "../../libs/jsruntime" }
logging = { path = "../../libs/logging" }
