[package]
name = "bee-lalrgen"
version = "0.0.0"
edition = "2021"
authors = ["BEE project contributors"]
publish = false

[dependencies]
anyhow = "1.0.75"
bee-macros = { path = "../macros" }
clap = { version = "4.4.7", features = ["derive", "env"] }
dashmap = "5.5.3"
humantime = "2.1.0"
im = "15.1.0"
indexmap = "2.1.0"
itertools = "0.11.0"
maplit = "1.0.2"
rayon = "1.8.0"
serde = { version = "1.0.192", features = ["derive", "rc"] }
serde_json = "1.0.108"
serde_yaml = "0.9.27"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "json"] }

[dev-dependencies]
assert_matches = "1.5.0"
pretty_assertions = "1.4.0"
test-log = { version = "0.2.13", default-features = false, features = ["trace"] }
