[package]
name = "bee-lalrgen"
version = "0.0.0"
edition = "2021"
authors = ["BEE project contributors"]
publish = false

[dependencies]
anyhow = "1.0.71"
bee-macros = { path = "../macros" }
clap = { version = "4.3.11", features = ["derive", "env"] }
dashmap = "5.5.0"
humantime = "2.1.0"
im = "15.1.0"
indexmap = "2.0.0"
itertools = "0.11.0"
maplit = "1.0.2"
rayon = "1.7.0"
serde = { version = "1.0.169", features = ["derive", "rc"] }
serde_json = "1.0.100"
serde_yaml = "0.9.22"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter", "json"] }

[dev-dependencies]
assert_matches = "1.5.0"
pretty_assertions = "1.4.0"
test-log = { version = "0.2.12", default-features = false, features = ["trace"] }
