// DO NOT EDIT THIS FILE BY HAND.
//
// This file was automagically generated by:
// bee-tools-codegen.js --input-stdin mod.rs.hbs

//<coverage:exclude>

mod helper;

// test cases
mod content_model_flags_test;
mod domjs_test;
mod entities_test;
mod escape_flag_test;
mod named_entities_test;
mod numeric_entities_test;
mod pending_spec_changes_test;
mod test1_test;
mod test2_test;
mod test3_test;
mod test4_test;
mod unicode_chars_problematic_test;
mod unicode_chars_test;

//</coverage:exclude>
