[package]
name = "bee-esgrammar"
version = "0.0.0"
edition = "2021"
authors = ["BEE project contributors"]
publish = false

[dependencies]
anyhow = "1.0.76"
bee-htmlparser = { path = "../htmlparser" }
bee-toydom = { path = "../toydom" }
clap = { version = "4.4.11", features = ["derive"] }
