// DO NOT EDIT THIS FILE BY HAND.
//
// This file was automagically generated with:
// template: libs/htmlparser/tests/html5lib_tests.rs.hbs

mod helper;

use helper::parse;
use helper::Scripting;
use helper::Test;

logging::init!();

#[test]
fn test_0000() {
    parse(Test {
        data: "<!doctype html><p>foo<search>bar<p>baz",
        document: vec![
            (0, "<!DOCTYPE html>"),
            (0, "<html>"),
            (1, "<head>"),
            (1, "<body>"),
            (2, "<p>"),
            (3, "\"foo\""),
            (2, "<search>"),
            (3, "\"bar\""),
            (3, "<p>"),
            (4, "\"baz\""),
        ],
        context_element: None,
        scripting: Scripting::Both,
    });
}

#[test]
fn test_0001() {
    parse(Test {
        data: "<!doctype html><search><p>foo</search>bar",
        document: vec![
            (0, "<!DOCTYPE html>"),
            (0, "<html>"),
            (1, "<head>"),
            (1, "<body>"),
            (2, "<search>"),
            (3, "<p>"),
            (4, "\"foo\""),
            (2, "\"bar\""),
        ],
        context_element: None,
        scripting: Scripting::Both,
    });
}

#[test]
fn test_0002() {
    parse(Test {
        data: "<!DOCTYPE html>xxx<svg><x><g><a><search><b>",
        document: vec![
            (0, "<!DOCTYPE html>"),
            (0, "<html>"),
            (1, "<head>"),
            (1, "<body>"),
            (2, "\"xxx\""),
            (2, "<svg svg>"),
            (3, "<svg x>"),
            (4, "<svg g>"),
            (5, "<svg a>"),
            (6, "<svg search>"),
            (2, "<b>"),
        ],
        context_element: None,
        scripting: Scripting::Both,
    });
}
