[package]
name = "bee-estree"
version = "0.0.0"
edition = "2021"
authors = ["BEE project contributors"]
publish = false

[dependencies]
anyhow = "1.0.75"
assert-json-diff = "2.0.2"
bee-jsparser = { path = "../jsparser", features = ["location"] }
clap = { version = "4.4.11", features = ["env", "derive", "wrap_help"] }
serde = { version = "1.0.193", features = ["derive", "rc"] }
serde_json = { version = "1.0.108", features = ["preserve_order"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "json"] }

[dev-dependencies]
anyhow = "1.0.75"
test-log = { version = "0.2.14", default-features = false, features = ["trace"] }
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "json"] }
