[package]
name = "bee-benches"
version = "0.0.0"
edition = "2018"
publish = false

[dev-dependencies]
criterion = "0.3"
criterion-cycles-per-byte = "0.1"

[[bench]]
name = "bench"
path = "src/bench_main.rs"
harness = false
