[package]
name = "bee-benches"
version = "0.0.0"
edition = "2021"
publish = false

[dev-dependencies]
criterion = "0.3.5"
criterion-cycles-per-byte = "0.1.2"

[[bench]]
name = "bench"
path = "src/bench_main.rs"
harness = false
