[package]
name = "bee-lmp"
version = "0.1.0"
authors = ["BEE project contributors"]
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.55"
bee-layout = { path = "../../libs/layout", features = ["service"] }
serde_json = "1.0.79"
structopt = "0.3.26"
