[package]
name = "bee-htmltokenizer"
version = "0.1.0"
edition = "2021"
authors = ["BEE project contributors"]
publish = false

[dependencies]
bytes = "1.5.0"
thiserror = "1.0.52"
tracing = "0.1.40"

[dev-dependencies]
anyhow = "1.0.77"
assert_matches = "1.5.0"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"

[lib]
bench = false
