[package]
name = "bee-htmltokenizer"
version = "0.1.0"
edition = "2021"
authors = ["BEE project contributors"]
publish = false

[dependencies]
bytes = "1.4.0"
thiserror = "1.0.44"
tracing = "0.1.37"

[dev-dependencies]
anyhow = "1.0.72"
assert_matches = "1.5.0"
serde = { version = "1.0.183", features = ["derive"] }
serde_json = "1.0.104"

[lib]
bench = false
