print(await typeof await undefined); ///="undefined"
print(await typeof await null); ///="object"
print(await typeof await true); ///="boolean"
print(await typeof await 1); ///="number"
print(await typeof await "hi"); ///="string"
print(await typeof await {}); ///="object"
print(await typeof await function() {}); ///="function"
print(await typeof await (() => 0)); ///="function"
print(await typeof await async function() {}); ///="function"
print(await typeof await (async () => 0)); ///="function"
