name: auto-merge

on:
  workflow_run:
    workflows:
      - ci
    types:
      - completed

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: |
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: actions/github-script@v6
        with:
          # Use a Personal Access Token instead of GITHUB_TOKEN.
          #
          # Scripts using GITHUB_TOKEN cannot trigger new workflow runs.
          # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#triggering-new-workflows-using-a-personal-access-token
          github-token: ${{secrets.GH_TOKEN}}
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.workflow_run.pull_requests[0].number,
            });
            if (pr.data.user.login !== process.env.ALLOWED_USER) {
              console.log(`Not Merged: User must be "${process.env.ALLOWED_USER}"`);
              return;
            }
            if (!pr.data.title.startsWith(process.env.ALLOWED_TITLE_PREFIX)) {
              console.log(`Not Merged: Title must start with "${process.env.ALLOWED_TITLE_PREFIX}"`);
              return;
            }
            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.workflow_run.pull_requests[0].number,
            });
            console.log('Merged successfully');
