# See https://bencher.dev/docs/how-to/github-actions/#pull-requests-from-forks
name: bench (upload)

on:
  workflow_run:
    workflows:
      - bench (PR)
    types:
      - completed

jobs:
  upload:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    env:
      BENCHMARK_RESULTS: benchmark_results.txt
      PR_EVENT: event.json
    steps:
      - name: Download Benchmark Results
        uses: dawidd6/action-download-artifact@v6
        with:
          name: ${{ env.BENCHMARK_RESULTS }}
          run_id: ${{ github.event.workflow_run.id }}
      - name: Download PR Event
        uses: dawidd6/action-download-artifact@v6
        with:
          name: ${{ env.PR_EVENT }}
          run_id: ${{ github.event.workflow_run.id }}
      - name: Export PR Event Data
        uses: actions/github-script@v6
        with:
          script: |
            let fs = require('fs');
            let prEvent = JSON.parse(fs.readFileSync(process.env.PR_EVENT, {encoding: 'utf8'}));
            core.exportVariable("PR_HEAD", prEvent.pull_request.head.ref);
            core.exportVariable("PR_BASE", prEvent.pull_request.base.ref);
            core.exportVariable("PR_BASE_SHA", prEvent.pull_request.base.sha);
            core.exportVariable("PR_NUMBER", prEvent.number);
      - uses: bencherdev/bencher@main
      - name: Upload benchmark results
        run: >-
          bencher run
          --project=bee-browser
          --token='${{ secrets.BENCHER_API_TOKEN }}'
          --branch="$PR_HEAD"
          --testbed=ubuntu-latest
          --start-point="$PR_BASE"
          --start-point-hash="$PR_BASE_SHA"
          --start-point-clone-thresholds
          --start-point-reset
          --err
          --github-actions='${{ secrets.GITHUB_TOKEN }}'
          --ci-number="$PR_NUMBER"
          --adapter=rust_criterion
          --file="$BENCHMARK_RESULTS"
