# See https://bencher.dev/docs/how-to/github-actions/#pull-requests-from-forks
name: bench (archive)

on:
  pull_request_target:
    types:
      - closed

permissions: {}

jobs:
  archive:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          submodules: recursive
      - uses: bencherdev/bencher@d2895af8c867c83b8fe766a6b84d8ccd4df5c315 # v0.6.10
      - name: Archive closed fork PR branch
        run: >-
          bencher archive
          --project=bee-browser
          --token="$BENCHER_API_TOKEN"
          --branch="$GITHUB_HEAD_REF"
        env:
          BENCHER_API_TOKEN: ${{ secrets.BENCHER_API_TOKEN }}
