# See https://bencher.dev/docs/how-to/github-actions/#pull-requests-from-forks
name: bench (archive)

on:
  pull_request_target:
    types:
      - closed

permissions: {}

jobs:
  archive:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          submodules: recursive
      - uses: bencherdev/bencher@0f8f620172ccd6225d40a7590598eb7b41718af8 # v0.6.2
      - name: Archive closed fork PR branch
        run: >-
          bencher archive
          --project=bee-browser
          --token="$BENCHER_API_TOKEN"
          --branch="$GITHUB_HEAD_REF"
        env:
          BENCHER_API_TOKEN: ${{ secrets.BENCHER_API_TOKEN }}
