# See https://bencher.dev/docs/how-to/github-actions/#pull-requests-from-forks
name: bench (PR)

on:
  pull_request:
    branches:
      - main
      - release
    types:
      - opened
      - reopened
      - edited
      - synchronize
    paths-ignore:
      - '**.md'

permissions: {}

jobs:
  bench:
    # Skip if this workflow is triggered by dependabot.
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          submodules: recursive
      - uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # v1
        with:
          toolchain: stable
          components: rustfmt
      - uses: davidlattimore/wild-action@b566cb94d30560824721753b60e67a4259a548cb # 0.8.0
      - uses: denoland/setup-deno@667a34cdef165d8d2b2e98dde39547c9daac7282 # v2.0.4
        with:
          deno-version-file: .tool-versions
      - name: Codegen
        run: make -j $(nproc) codegen
      - uses: bencherdev/bencher@8151077aa7b1bceaac11c4b308265417cae60e2b # v0.5.10
      - name: Benchmark tests
        run: >-
          make bench >benchmark_results.txt
      - name: Upload Benchmark Results
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: benchmark_results.txt
          path: ./benchmark_results.txt
          retention-days: 1
      - name: Upload GitHub Pull Request Event
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: event.json
          path: ${{ github.event_path }}
          retention-days: 1
