name: bench

on:
  push:
    branches:
      - main
      - release
      - trial-*
    paths-ignore:
      - '**.md'
  # Don't run this workflow on pull_request.
  # This workflow uses secrets.
  pull_request_target:
    branches:
      - main
      - release
    paths-ignore:
      - '**.md'

env:
  DENO_DIR: /tmp/deno

jobs:
  bench:
    # Skip if this workflow is triggered by dependabot.
    if: ${{ github.actor != 'dependabot[bot]' }}
    # a temporal fix for llvm/llvm-project#99502
    #runs-on: ubuntu-latest
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: false
          submodules: recursive
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: 'clippy, rustfmt'
      - uses: Swatinem/rust-cache@v2
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v1.x
      - name: Install LLVM
        run: |
          sh -x tools/bin/github_actions_install_llvm.sh
      - name: Codegen
        run: make codegen
      - uses: bencherdev/bencher@main
      - name: Benchmark tests (push)
        if: ${{ github.event_name == 'push' }}
        run: |
          bencher run --err --adapter=rust_criterion make bench
        env:
          BENCHER_PROJECT: bee-browser
          BENCHER_API_TOKEN: ${{ secrets.BENCHER_API_TOKEN }}
          BENCHER_BRANCH: ${{ github.ref_name }}
          BENCHER_TESTBED: ubuntu-latest
      - name: Benchmark tests (pull_request_target)
        if: ${{ github.event_name == 'pull_request_target' }}
        run: |
          bencher run --err --adapter=rust_criterion \
            --branch-start-point='${{ github.base_ref }}' \
            --branch-start-point-hash='${{ github.event.pull_request.base.sha }}' \
            --ci-number='${{ github.event.number }}' \
            --github-actions='${{ secrets.GITHUB_TOKEN }}' \
            make bench
        env:
          BENCHER_PROJECT: bee-browser
          BENCHER_API_TOKEN: ${{ secrets.BENCHER_API_TOKEN }}
          BENCHER_BRANCH: ${{ github.event.number }}/merge
          BENCHER_TESTBED: ubuntu-latest
