name: build

on:
  workflow_call:
    inputs:
      runner:
        default: ubuntu-latest
        required: false
        type: string
      rust:
        default: stable
        required: false
        type: string
  workflow_dispatch:
    inputs:
      runner:
        default: ubuntu-latest
        required: false
        type: choice
        options:
          - ubuntu-latest
          - macos-latest
      rust:
        default: stable
        required: false
        type: choice
        options:
          - stable
          - nightly

permissions: {}

jobs:
  build:
    runs-on: ${{ inputs.runner }}
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          submodules: recursive
      - uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # v1
        with:
          toolchain: ${{ inputs.rust }}
          components: clippy, rustfmt
      - uses: davidlattimore/wild-action@0bbbfa5df4380cab8e63cb8505a1ce65e1d10203 # 0.9.0
      - uses: denoland/setup-deno@667a34cdef165d8d2b2e98dde39547c9daac7282 # v2.0.4
        with:
          deno-version-file: .tool-versions
      - uses: taiki-e/install-action@682e7d9e49c5e653d371fc6adbda67653461378a # v2.82.4
        with:
          tool: nextest, zizmor
      - name: Codegen
        run: make -j $(nproc) codegen
      - name: Check
        run: make check
      - name: Build
        run: make build
      - name: Build (release)
        run: make build OPTIONS='-r'
      - name: Run tests
        run: make test
      - name: Run tc39/test262
        run: |
          make test262 ARGS='' OOP=1
          echo 'panics:'
          jq -r '.results[] | select(.status == "panic") | "  " + .file' test262.json
