name: ci

on:
  push:
    branches:
      - main
      - release
      - trial-*
    paths-ignore:
      - '**.md'

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
  coverage:
    needs:
      - build
    uses: ./.github/workflows/coverage.yml
    secrets: inherit
