name: ci

on:
  push:
    branches:
      - main
      - release
      - trial-*
    paths-ignore:
      - '**.md'

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      # a temporal fix for llvm/llvm-project#99502
      runner: ubuntu-24.04
