name: ci

on:
  push:
    branches:
      - main
      - release
      - trial-*
    paths-ignore:
      - '**.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  build:
    uses: ./.github/workflows/build.yml
    permissions:
      contents: read
