name: coverage

on:
  workflow_call:

env:
  DENO_DIR: /tmp/deno

jobs:
  coverage:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      # TODO: Caching dependencies
      - name: Install nextest
        uses: taiki-e/install-action@nextest
      - name: Install grcov
        uses: taiki-e/install-action@grcov
      - name: Generate coverage data
        run: |
          make coverage-lcov
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v3
        with:
          token: '${{ secrets.CODECOV_TOKEN }}'
          files: target/coverage/lcov.info
