name: coverage

on:
  push:
    branches:
      - main
      - release
      - trial-*
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
      - release
    paths-ignore:
      - '**.md'

env:
  DENO_DIR: /tmp/deno

jobs:
  coverage:
    # Skip if this workflow is triggered by dependabot.
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    continue-on-error: true
    permissions:
      contents: read
      id-token: write
    steps:
      # Remove packages in order to avoid "No space left on device" error in `make coverage`.
      - uses: jlumbroso/free-disk-space@v1.3.1
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          submodules: recursive
      - uses: dtolnay/rust-toolchain@stable
      - uses: rui314/setup-mold@v1
      - uses: Swatinem/rust-cache@v2
      - uses: denoland/setup-deno@v2
        with:
          deno-version-file: .tool-versions
      - name: Cache Deno dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env. DENO_DIR }}
          key: deno-dir-${{ runner.os }}-${{ hashFiles('deno.lock') }}
      - uses: taiki-e/install-action@nextest
      - uses: taiki-e/install-action@cargo-llvm-cov
      - name: Codegen
        run: make codegen
      - name: Generate code coverage
        run: |
          make coverage LLVM_COV_ARGS='--codecov --output-path=codecov.json' TEST262_ARGS=''
      - uses: codecov/codecov-action@v5
        with:
          files: codecov.json
          fail_ci_if_error: true
          use_oidc: true
