name: coverage

on:
  push:
    branches:
      - main
      - release
      - trial-*
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
      - release
    paths-ignore:
      - '**.md'

permissions: {}

jobs:
  coverage:
    # Skip if this workflow is triggered by dependabot.
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    continue-on-error: true
    permissions:
      contents: read
      id-token: write
    steps:
      # Remove packages in order to avoid "No space left on device" error in `make coverage`.
      - uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # v1.3.1
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          submodules: recursive
      - uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # v1
        with:
          toolchain: stable
          components: rustfmt
      # The following error occurs when using davidlattimore/wild-action in this workflow.
      #
      # ```
      # error: linker `clang` not found
      #   |
      #   = note: No such file or directory (os error 2)
      # ```
      #
      # Probably, jlumbroso/free-disk-space uninstalls clang-* and this causes the error.
      - uses: rui314/setup-mold@725a8794d15fc7563f59595bd9556495c0564878 # staging
      - uses: denoland/setup-deno@e95548e56dfa95d4e1a28d6f422fafe75c4c26fb # v2.0.3
        with:
          deno-version-file: .tool-versions
      - uses: taiki-e/install-action@385db9cc6bf65d19775b02084a4b698eaca9a4f2 # v2.68.19
        with:
          tool: cargo-llvm-cov, nextest
      - name: Codegen
        run: make -j $(nproc) codegen
      - name: Generate code coverage
        run: |
          make coverage LLVM_COV_ARGS='--codecov --output-path=codecov.json'
      - uses: codecov/codecov-action@1af58845a975a7985b0beb0cbe6fbbb71a41dbad # v5.5.3
        with:
          files: codecov.json
          fail_ci_if_error: true
          use_oidc: true
