name: coverage

on:
  workflow_run:
    workflows:
      - ci
    types:
      - completed

env:
  DENO_DIR: /tmp/deno

jobs:
  coverage:
    runs-on: ubuntu-latest
    if: |
      github.event.workflow_run.event == 'push' &&
      github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Cache for deno
        uses: actions/cache@v3
        with:
          path: |
            $DENO_DIR
          key: |
            ${{ runner.os }}-deno-${{ hashFiles('tools/deps.js') }}
          restore-keys: |
            ${{ runner.os }}-deno-
      - name: Clean
        run: |
          make clean
      - name: Prepare GitHub CI
        run: |
          make github-ci
      - name: Generate coverage data
        run: |
          make coverage-lcov
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v3
        with:
          token: '${{ secrets.CODECOV_TOKEN }}'
          file: target/coverage/lcov.info
