name: pull-request

on:
  pull_request:
    branches:
      - main
      - release
    paths-ignore:
      - '**.md'

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
  coverage:
    uses: ./.github/workflows/coverage.yml
    secrets: inherit
