name: pull-request

on:
  pull_request:
    branches:
      - main
      - release
    paths-ignore:
      - '**.md'

# Don't run jobs which use secrets.
jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      # a temporal fix for llvm/llvm-project#99502
      runner: ubuntu-24.04
