name: pull-request

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  build:
    uses: bee-browser/prototype/.github/workflows/build.yml@main
    secrets: inherit
  coverage:
    needs:
      - build
    uses: bee-browser/prototype/.github/workflows/coverage.yml@main
    secrets: inherit
